version: '3'

services:
  # Laravel application (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: old-docker/Dockerfile
    volumes:
      - .:/var/www/html/estacionamento
    networks:
      - backend

  # Nginx
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/estacionamento
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

  # MongoDB
  mongodb:
    image: mongo
    container_name: estacionamentodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
