version: '3'

services:
  # Laravel application (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: old-docker/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - backend

  # Nginx
  web:
    image: nginx:alpine
    ports:
      - "80:80"  # Mapeia a porta 80 do host para a porta 80 do container
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
